-- @Exception

function foo()
  return 1
end

function foo()
  return 2
end
